[[headers]]
    for = "/*"
    [headers.values]
    cache-control = '''
    public,
    max-age=43200'''

[[redirects]]
    from = "/*"
    to = "https://infoblock-cdn.netlify.app/404"
    status = 404